# Generated by Django 3.2 on 2021-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=400)),
                ('image_url', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('movie_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
